[game]
desc = "A medium roleplay fork based around the paranormal with unique content and almost all unique art, all with a focus on lore and immersion."
lobbyenabled = true
lobbyduration = 600
round_restart_time = 300
contraband_examine = false
role_timer_override = "QBTemporaryPlaytimeReq"
soft_max_players = 60
#map_pool = "QuantumBlueMapPool" #TODO: Actually make this

[movement]
mob_pushing = false

[infolinks]
github = "https://github.com/QuantumBlueSS14/Quantum-Blue-New"

[net]
max_connections = 1024
tickrate = 30

[netres]
limit    = 10.0

[admin]
see_own_notes   = true
deadmin_on_join = true
allow_multi_server_play = true
[admin.alert]
min_players_sharing_connection = 2

[server]
id = "quantumblue"
#rules_file = "QuantumBlueRuleset" TODO: Port this in from the old repo and touch it up
uptime_restart_minutes = 1440 # 24h

# general mrp stuff
[ic]
flavor_text = true
punctuation = true
restricted_names = false

[atmos]
space_wind = true

[shuttle]
emergency_early_launch_allowed = true

[biomass]
easy_mode = false

[control]
storage_limit = 2

[whitelist]
enabled = true
